"""Default settings and editable configuration schema."""

from __future__ import annotations

DEFAULT_CONFIG = {
    "device": {
        "name": "PiConnect Speaker",
        "append_hostname": False,
        "type": "speaker",
        "timezone": "Etc/UTC",
        "language": "en",
    },
    "web": {
        "host": "0.0.0.0",
        "port": 8080,
        "auth_mode": "none",
        "auth_pin": "",
        "theme": "system",
    },
    "audio": {
        "backend": "alsa",
        "device_selection": "auto",
        "device": "default",
        "fallback": "wait",
        "mixer": "softvol",
        "alsa_mixer_control": "PCM",
        "alsa_mixer_device": "default",
        "alsa_mixer_index": 0,
        "format": "S16",
        "dither": "tpdf",
    },
    "volume": {
        "startup_volume_percent": 40,
        "volume_control": "log",
        "volume_range_db": 60,
        "normalisation_enabled": True,
        "normalisation_method": "dynamic",
        "normalisation_gain_type": "auto",
        "normalisation_pregain_db": 0.0,
        "normalisation_threshold_dbfs": -2.0,
    },
    "quality": {
        "bitrate_kbps": 320,
        "cache_enabled": True,
        "cache_path": "/var/cache/pi-connect-speaker/audio",
        "system_cache_path": "/var/cache/pi-connect-speaker/system",
        "cache_size_limit": "512M",
        "gapless_enabled": True,
        "autoplay_enabled": True,
    },
    "network": {
        "wait_for_network": True,
        "interface": "wlan0",
        "connectivity_host": "1.1.1.1",
        "restart_after_offline_seconds": 60,
        "retry_interval_seconds": 5,
    },
    "stability": {
        "buffer_preset": "stable",
        "command_timeout_seconds": 10,
        "health_check_interval_seconds": 20,
        "watchdog_enabled": False,
        "require_audio_device_before_start": False,
    },
    "service": {
        "librespot_path": "librespot",
        "spotify_service_name": "pi-connect-speaker-librespot.service",
        "web_service_name": "pi-connect-speaker.service",
        "autostart": True,
        "log_level": "info",
        "zeroconf_backend": "auto",
        "zeroconf_port": 0,
        "zeroconf_interface": "",
    },
    "diagnostics": {
        "log_lines": 200,
        "auto_refresh_seconds": 10,
        "test_sound_command": "speaker-test",
        "test_sound_duration_seconds": 2,
        "test_sound_frequency_hz": 440,
        "show_command_preview": True,
    },
    "backup": {
        "enabled": True,
        "directory": "/etc/pi-connect-speaker/backups",
        "keep_last": 20,
    },
    "profiles": {
        "directory": "/etc/pi-connect-speaker/profiles",
    },
    "librespot": {
        "enable_oauth": False,
        "oauth_port": 0,
        "access_token": "",
        "username": "",
        "extra_args": [],
    },
}


SECTION_LABELS = {
    "device": "Device",
    "web": "Web UI",
    "audio": "Audio",
    "volume": "Volume",
    "quality": "Quality",
    "network": "Network",
    "stability": "Stability",
    "service": "Service",
    "diagnostics": "Diagnostics",
    "backup": "Backup",
    "profiles": "Profiles",
    "librespot": "Librespot",
}


SECTION_ORDER = [
    "device",
    "web",
    "audio",
    "volume",
    "quality",
    "network",
    "stability",
    "service",
    "diagnostics",
    "backup",
    "profiles",
    "librespot",
]


CONFIG_SCHEMA = {
    "device": [
        {"key": "name", "label": "Device name", "type": "string", "required": True},
        {"key": "append_hostname", "label": "Append hostname", "type": "boolean"},
        {
            "key": "type",
            "label": "Spotify device type",
            "type": "enum",
            "choices": [
                "speaker",
                "avr",
                "audiodongle",
                "tv",
                "computer",
                "castaudio",
            ],
        },
        {"key": "timezone", "label": "Timezone", "type": "string"},
        {"key": "language", "label": "Language", "type": "enum", "choices": ["en"]},
    ],
    "web": [
        {"key": "host", "label": "Bind address", "type": "string", "required": True},
        {"key": "port", "label": "Port", "type": "integer", "min": 1, "max": 65535},
        {"key": "auth_mode", "label": "Authentication", "type": "enum", "choices": ["none", "pin"]},
        {"key": "auth_pin", "label": "PIN", "type": "secret"},
        {"key": "theme", "label": "Theme", "type": "enum", "choices": ["system", "light", "dark"]},
    ],
    "audio": [
        {
            "key": "backend",
            "label": "Backend",
            "type": "enum",
            "choices": ["alsa", "rodio", "pulseaudio", "pipe", "subprocess", "gstreamer"],
        },
        {"key": "device_selection", "label": "Device selection", "type": "enum", "choices": ["auto", "manual"]},
        {"key": "device", "label": "Audio device", "type": "string"},
        {"key": "fallback", "label": "Fallback", "type": "enum", "choices": ["wait", "default", "disabled"]},
        {"key": "mixer", "label": "Mixer", "type": "enum", "choices": ["softvol", "alsa"]},
        {"key": "alsa_mixer_control", "label": "ALSA mixer control", "type": "string"},
        {"key": "alsa_mixer_device", "label": "ALSA mixer device", "type": "string"},
        {"key": "alsa_mixer_index", "label": "ALSA mixer index", "type": "integer", "min": 0, "max": 32},
        {"key": "format", "label": "Output format", "type": "enum", "choices": ["S16", "S24", "S24_3", "S32", "F32", "F64"]},
        {"key": "dither", "label": "Dither", "type": "enum", "choices": ["none", "gpdf", "tpdf", "tpdf_hp"]},
    ],
    "volume": [
        {"key": "startup_volume_percent", "label": "Startup volume", "type": "integer", "min": 0, "max": 100, "unit": "%"},
        {"key": "volume_control", "label": "Volume curve", "type": "enum", "choices": ["cubic", "fixed", "linear", "log"]},
        {"key": "volume_range_db", "label": "Volume range", "type": "integer", "min": 1, "max": 120, "unit": "dB"},
        {"key": "normalisation_enabled", "label": "Volume normalisation", "type": "boolean"},
        {"key": "normalisation_method", "label": "Normalisation method", "type": "enum", "choices": ["basic", "dynamic"]},
        {"key": "normalisation_gain_type", "label": "Gain type", "type": "enum", "choices": ["track", "album", "auto"]},
        {"key": "normalisation_pregain_db", "label": "Pregain", "type": "float", "min": -20, "max": 20, "unit": "dB"},
        {"key": "normalisation_threshold_dbfs", "label": "Threshold", "type": "float", "min": -20, "max": 0, "unit": "dBFS"},
    ],
    "quality": [
        {"key": "bitrate_kbps", "label": "Bitrate", "type": "enum", "choices": [96, 160, 320], "unit": "kbps"},
        {"key": "cache_enabled", "label": "Audio cache", "type": "boolean"},
        {"key": "cache_path", "label": "Audio cache path", "type": "string"},
        {"key": "system_cache_path", "label": "System cache path", "type": "string"},
        {"key": "cache_size_limit", "label": "Cache size limit", "type": "string"},
        {"key": "gapless_enabled", "label": "Gapless playback", "type": "boolean"},
        {"key": "autoplay_enabled", "label": "Autoplay", "type": "boolean"},
    ],
    "network": [
        {"key": "wait_for_network", "label": "Wait for network", "type": "boolean"},
        {"key": "interface", "label": "Interface", "type": "string"},
        {"key": "connectivity_host", "label": "Connectivity host", "type": "string"},
        {"key": "restart_after_offline_seconds", "label": "Offline restart", "type": "integer", "min": 0, "max": 3600, "unit": "s"},
        {"key": "retry_interval_seconds", "label": "Retry interval", "type": "integer", "min": 1, "max": 300, "unit": "s"},
    ],
    "stability": [
        {"key": "buffer_preset", "label": "Buffer preset", "type": "enum", "choices": ["stable", "balanced", "low_latency", "custom"]},
        {"key": "command_timeout_seconds", "label": "Command timeout", "type": "integer", "min": 1, "max": 120, "unit": "s"},
        {"key": "health_check_interval_seconds", "label": "Health check interval", "type": "integer", "min": 5, "max": 3600, "unit": "s"},
        {"key": "watchdog_enabled", "label": "Systemd watchdog", "type": "boolean"},
        {"key": "require_audio_device_before_start", "label": "Require audio device", "type": "boolean"},
    ],
    "service": [
        {"key": "librespot_path", "label": "Librespot path", "type": "string", "required": True},
        {"key": "spotify_service_name", "label": "Spotify service", "type": "string", "required": True},
        {"key": "web_service_name", "label": "Web service", "type": "string", "required": True},
        {"key": "autostart", "label": "Autostart", "type": "boolean"},
        {"key": "log_level", "label": "Log level", "type": "enum", "choices": ["quiet", "info", "verbose"]},
        {"key": "zeroconf_backend", "label": "Zeroconf backend", "type": "enum", "choices": ["auto", "avahi", "dns-sd", "libmdns"]},
        {"key": "zeroconf_port", "label": "Zeroconf port", "type": "integer", "min": 0, "max": 65535},
        {"key": "zeroconf_interface", "label": "Zeroconf interface", "type": "string"},
    ],
    "diagnostics": [
        {"key": "log_lines", "label": "Log lines", "type": "integer", "min": 20, "max": 2000},
        {"key": "auto_refresh_seconds", "label": "Auto refresh", "type": "integer", "min": 0, "max": 300, "unit": "s"},
        {"key": "test_sound_command", "label": "Test sound command", "type": "enum", "choices": ["speaker-test", "aplay", "disabled"]},
        {"key": "test_sound_duration_seconds", "label": "Test sound duration", "type": "integer", "min": 1, "max": 30, "unit": "s"},
        {"key": "test_sound_frequency_hz", "label": "Test sound frequency", "type": "integer", "min": 100, "max": 12000, "unit": "Hz"},
        {"key": "show_command_preview", "label": "Show command preview", "type": "boolean"},
    ],
    "backup": [
        {"key": "enabled", "label": "Back up before save", "type": "boolean"},
        {"key": "directory", "label": "Backup directory", "type": "string", "required": True},
        {"key": "keep_last", "label": "Backups to keep", "type": "integer", "min": 1, "max": 200},
    ],
    "profiles": [
        {"key": "directory", "label": "Profile directory", "type": "string", "required": True},
    ],
    "librespot": [
        {"key": "enable_oauth", "label": "OAuth login", "type": "boolean"},
        {"key": "oauth_port", "label": "OAuth port", "type": "integer", "min": 0, "max": 65535},
        {"key": "access_token", "label": "Access token", "type": "secret"},
        {"key": "username", "label": "Cached username", "type": "string"},
        {"key": "extra_args", "label": "Extra arguments", "type": "string_list"},
    ],
}
